name: Build 32-bit WsRtd.dll

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.27.0'

    - name: Configure for 32-bit
      run: cmake -B build -A Win32

    - name: Build DLL
      run: cmake --build build --config Release

    - name: Upload DLL
      uses: actions/upload-artifact@v4
      with:
        name: WsRtd-32
        path: build/Release/WsRtd.dll
